Repository rsksmart/rif-identity-docs, pull requests merged in 2020-10, with the labels that each got.

#2 Holder and Issuer App Documentation
  Gemfile.lock
  assets/img/ssi/applications/holder-app/create-account.jpg
  assets/img/ssi/applications/holder-app/credential-display.jpg
  assets/img/ssi/applications/holder-app/request-credential.jpg
  assets/img/ssi/applications/issuer-app/credential-list.jpg
  assets/img/ssi/applications/issuer-app/sign-in.jpg
  ssi/applications.markdown
  ssi/applications/holder-app.markdown
  ssi/applications/index.markdown
  ssi/applications/issuer-app.markdown
Labels: documentation, enhancement

#5 Update _config.yml
  _config.yml
Labels: bug, enhancement

#3 Convey service documentation
  ssi/services.markdown
  ssi/services/convey-service.markdown
  ssi/services/index.markdown
Labels: documentation, enhancement

#1 SSI Specs
  _includes/ref.html
  assets/img/ssi/06_wallet_setup.png
  assets/img/ssi/07_persona_detection.png
  assets/img/ssi/08_did_auth.png
  assets/img/ssi/09_credential_requests.png
  definitions.markdown
  references.markdown
  ssi/services.markdown
  ssi/services/convey-service.markdown
  ssi/services/index.markdown
  ssi/specs/comm-declarative-details.markdown
  ssi/specs/convey-service.markdown
  ssi/specs/credential-requests.markdown
  ssi/specs/did-auth.markdown
  ssi/specs/encryption-layout.markdown
  ssi/specs/identity-layout.markdown
  ssi/specs/index.markdown
  ssi/specs/presentation-timestamps.markdown
Labels: enhancement

#7 Fix links
  README.md
  _includes/ref.html
  about.markdown
  definitions.markdown
  index.markdown
  ssi/applications/holder-app.markdown
  ssi/applications/index.markdown
  ssi/applications/issuer-app.markdown
  ssi/services/convey-service.markdown
  ssi/services/index.markdown
  ssi/specs/credential-requests.markdown
  ssi/specs/did-auth.markdown
  ssi/specs/encryption-layout.markdown
  ssi/specs/identity-layout.markdown
  ssi/specs/index.markdown
Labels: bug

#16 Update index.markdown
  index.markdown
Labels: documentation, enhancement

#20 Data vault file paths
  data-vault/cpinner/architecture.markdown
  data-vault/cpinner/cpinner-client.markdown
  data-vault/cpinner/cpinner-provider.markdown
  data-vault/cpinner/cpinner-service.markdown
  data-vault/cpinner/index.markdown
Labels: enhancement
